# Generated by Django 5.1 on 2024-09-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(help_text="A short introduction or summary of the post recommended words '30' "),
        ),
    ]
