# Generated by Django 5.1 on 2024-09-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNest', '0002_alter_post_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="recommend size '440x220'", null=True, upload_to='thumbnails/'),
        ),
    ]
