# Generated by Django 5.1 on 2024-08-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNest', '0002_rename_image_post_main_image_post_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
