# Generated by Django 5.1 on 2024-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNest', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default='this is an example', help_text='A short introduction or summary of the post', max_length=300),
            preserve_default=False,
        ),
    ]
