# Generated by Django 5.1 on 2024-08-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNest', '0013_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
