# Generated by Django 5.1 on 2024-08-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNest', '0017_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
